name: aws
on:
    push:
      branches:
        - main

env:
    REPONAME: ${{ github.event.repository.name }}
    WORKSPACE: ${{ github.workspace }}
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_REGION: ap-southeast-2

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          
      - name: Print terraform version
        run: terraform version
      
      - name: Export AWS Login Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $AWS_ACCESS_KEY_ID
          export AWS_REGION="ap-southeast-2"
          
      - name: Initalize Terraform
        run: terraform init

      - name: terraform plan
        run: terraform plan 

      - name: terraform apply
        run: terraform apply